modLoader="javafml"
loaderVersion="[4,)"
issueTrackerURL="https://github.com/Mrbysco/ElytraCancel/issues"
license="MIT"

[[mods]]
modId="elytracancel"
version="${file.jarVersion}"
displayName="Elytra Cancel"
displayURL="https://www.curseforge.com/minecraft/mc-mods/elytra-cancel"
authors="Mrbysco"
credits="Nekomaster1000 for the idea"
description='''
Allows canceling elytra flight mid-air by sneaking
'''

[[dependencies.elytracancel]]
modId="minecraft"
type="required"
versionRange="[26.1.1,)"
ordering="NONE"
side="BOTH"
[[mixins]]
config="elytracancel.mixins.json"